version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:23.5.0.0
    container_name: oracle-23ai
    ports:
      - "1521:1521"      # Oracle Database
      - "2484:2484"      # Oracle REST Data Services
      - "8080:8080"      # Enterprise Manager
    environment:
      - ORACLE_PWD=Oradoc_db1
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_NLS_CHARACTERSET=AL32UTF8
      - ORACLE_NLS_NCHAR_CHARACTERSET=AL32UTF8
    volumes:
      - ./init.sql:/opt/oracle/scripts/startup/01-init.sql:ro
      - oracle_data:/opt/oracle/oradata
      - oracle_backup:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oradoc_db1@//localhost:1521/FREE", "AS", "SYSDBA", "-c", "SELECT 1 FROM dual"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 300s
    restart: unless-stopped
    networks:
      - helidon-network

  # Opcional: Agregar un cliente SQL para debugging
  sqlplus-client:
    image: container-registry.oracle.com/database/free:23.5.0.0
    container_name: sqlplus-client
    depends_on:
      oracle-db:
        condition: service_healthy
    volumes:
      - ./sqlplus-init.sql:/opt/oracle/scripts/startup/01-sqlplus-init.sql:ro
    command: >
      bash -c "
        echo 'Esperando a que Oracle Database esté listo...' &&
        while ! sqlplus -L helidon_user/helidon123@//oracle-db:1521/FREE -c 'SELECT 1 FROM dual' > /dev/null 2>&1; do
          echo 'Esperando...' &&
          sleep 10
        done &&
        echo 'Oracle Database está listo!' &&
        echo 'Conectando como helidon_user...' &&
        sqlplus helidon_user/helidon123@//oracle-db:1521/FREE
      "
    networks:
      - helidon-network
    profiles:
      - debug

volumes:
  oracle_data:
    driver: local
  oracle_backup:
    driver: local

networks:
  helidon-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
